// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package partial

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Error404() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"flex items-center h-screen p-16 bg-gray-50 text-gray-800\"><div class=\"container flex flex-col items-center justify-center px-5 mx-auto my-8\"><div class=\"max-w-md text-center\"><h2 class=\"mb-8 font-extrabold text-9xl text-gray-400\"><span class=\"sr-only\">Error</span>404</h2><p class=\"text-2xl font-semibold md:text-3xl\">Sorry, we couldn't find this page.</p><p class=\"mt-4 mb-8 text-gray-600\">But dont worry, you can find plenty of other things on our homepage.</p><a rel=\"noopener noreferrer\" href=\"/\" class=\"px-8 py-3 font-semibold rounded bg-violet-600 text-gray-50\">Back to homepage</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
