// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package partial

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col max-w-md p-6 rounded-md sm:p-10 dark:bg-gray-900 dark:text-gray-100\"><div class=\"mb-8 text-center\"><h1 class=\"my-3 text-4xl font-bold\">Sign in</h1><p class=\"text-sm dark:text-gray-400\">Sign in to access your account</p></div><form novalidate=\"\" action=\"\" class=\"space-y-12\"><div class=\"space-y-4\"><div><label for=\"email\" class=\"block mb-2 text-sm\">Email address</label> <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"leroy@jenkins.com\" class=\"w-full px-3 py-2 border rounded-md dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100\"></div><div><div class=\"flex justify-between mb-2\"><label for=\"password\" class=\"text-sm\">Password</label> <a rel=\"noopener noreferrer\" href=\"#\" class=\"text-xs hover:underline dark:text-gray-400\">Forgot password?</a></div><input type=\"password\" name=\"password\" id=\"password\" placeholder=\"*****\" class=\"w-full px-3 py-2 border rounded-md dark:border-gray-700 dark:bg-gray-900 dark:text-gray-100\"></div></div><div class=\"space-y-2\"><div><button type=\"button\" class=\"w-full px-8 py-3 font-semibold rounded-md dark:bg-violet-400 dark:text-gray-900\">Sign in</button></div><p class=\"px-6 text-sm text-center dark:text-gray-400\">Don't have an account yet? <a rel=\"noopener noreferrer\" href=\"#\" class=\"hover:underline dark:text-violet-400\">Sign up</a>.</p></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
