// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ResetToken struct {
	Token     string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Name          string
	Password      string
	EmailVerified pgtype.Bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
