// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(email, name, password)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Email    string
	Name     string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Email, arg.Name, arg.Password)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id,
    password,
    email_verified
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserRow struct {
	ID            pgtype.UUID
	Password      string
	EmailVerified pgtype.Bool
}

func (q *Queries) GetUser(ctx context.Context, email string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i GetUserRow
	err := row.Scan(&i.ID, &i.Password, &i.EmailVerified)
	return i, err
}

const updatePasswordUser = `-- name: UpdatePasswordUser :exec
UPDATE users
SET password = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdatePasswordUserParams struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) UpdatePasswordUser(ctx context.Context, arg UpdatePasswordUserParams) error {
	_, err := q.db.Exec(ctx, updatePasswordUser, arg.ID, arg.Password)
	return err
}
